FROM ubuntu AS base

# Disable interactive prompts so the script can run unattended in CI/CD
RUN export DEBIAN_FRONTEND=noninteractive

# Install MariaDB (Missing the configuration for vi command)
RUN apt update
RUN apt install -y mariadb-server
# RUN service mariadb start

# Configure Database (I think you put the commands below into a SQL file)

# (Skip, not working) Configure firewall for Database

# Configure Database (I think you put the commands below into a SQL file)
COPY ./db-configure.sql /
# RUN mysql < /db-configure.sql

# Run sql script
COPY ./db-load-script.sql /
# RUN mysql < /db-load-script.sql

# Install required packages
RUN apt install -y apache2
RUN apt install -y php 
# (Export fixed this) Need to feed into cli 
# 5. Asia
# 46. Kuala_Lumpur
# Skipped the firewall installation
RUN apt install -y php-mysqlnd 

# Configure httpd
RUN sed -i 's/index.html/index.php/g' /etc/apache2/apache2.conf

# Start apache2
# RUN service apache2 start

# Download code
# You can fork the repository, than make changes to the index.php so the below code would be unnessary
RUN apt install -y git

# Need to clean directory before can clone
RUN rm -r /var/www/html/
RUN git clone https://github.com/jonathan-kee/learning-app-ecommerce.git /var/www/html/

# Add .env file for index.php to connect to database 
COPY ./.env /var/www/html/

# Test
# RUN apt install -y curl
# RUN curl http://localhost

COPY ./start.sh /
RUN chmod +x /start.sh

COPY ./stop.sh /
RUN chmod +x /stop.sh

# This replaces your four RUN lines
CMD ["/bin/bash", "/start.sh"]