Vagrant.configure("2") do |config|
  # A box is a pre-configured virtual machine image that you can use as a starting point for your virtual machine  
  config.vm.define "server1" do |server1|
    server1.vm.box = "stromweld/windows-11"
    server1.vm.box_version = "202511.21.0"
  end

  # A box is a pre-configured virtual machine image that you can use as a starting point for your virtual machine  
  config.vm.define "server2" do |server2|
    server2.vm.box = "stromweld/windows-11"
    server2.vm.box_version = "202511.21.0"
  end

  # https://developer.hashicorp.com/vagrant/docs/provisioning/shell#external-script
  config.vm.provision "shell" do |ps|
    ps.privileged = true
    # Apparently the below line is causing error when provisioning
    # ps.powershell_elevated_interactive = true
    ps.path = "scripts/installOpenSSH.ps1"
  end
 
end