Vagrant.configure("2") do |config|
  # A box is a pre-configured virtual machine image that you can use as a starting point for your virtual machine
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.box_version = "2021.05.15"
end