Vagrant.configure("2") do |config|
  # A box is a pre-configured virtual machine image that you can use as a starting point for your virtual machine  
  config.vm.box = "gyptazy/proxmox8.1-arm64"
  config.vm.box_version = "1.0.0"

  # ----------------- Bridge mode (Not working) -----------------
  # Using bridge mode, this will ask you what network interface to attach to.
  # Try to choose 1) en0: Wi-Fi
  # So instead of 10.0.0.x , should now be 192.168.1.x
  
  #config.vm.network "public_network", 
  #use_dhcp_assigned_default_route: true,
  #bridge: "en0: Wi-Fi"
  # ----------------- Bridge mode (Not working) -----------------
  


  # ----------------- SSH remote capture (Not working) -----------------
  # Map host port 2222 to guest port 22
  # config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"

  # Ensure the Windows Firewall allows SSH (Optional but helpful)
  # config.vm.provision "shell", inline: "netsh advfirewall firewall add rule name='Allow SSH' dir=in action=allow protocol=TCP localport=22"
  # ----------------- SSH remote capture (Not working) -----------------



  # ----------------- Fix Device manager issue (Not working) -----------------
  # https://developer.hashicorp.com/vagrant/docs/provisioning/file
  # config.vm.provision "file", source: "drivers/arm64", destination: "~/Desktop/drivers/arm64"
  # ----------------- Fix Device manager issue (Not working) -----------------
  
end