name: 2 Tier

on:
  workflow_dispatch:

jobs:
  job-one:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # Output for the below command
      # /home/vagrant/actions-runner/_work/DNS-Container/DNS-Container
      - name: Print Working Directory
        run: pwd  

      - name: Change Working Directory & Print dockerfile
        run: | 
          cd 2tier
          cat dockerfile

      - name: Docker Build
        run: docker build --tag 2tier:latest .

      - name: Docker Run
        run: |
          docker run --detach \
          --name=2tier \
          --privileged \
          --restart=always \
          --publish 127.0.0.1:80:80/tcp \
          --publish 127.0.0.1:3306:3306/tcp \
          2tier:latest bash -c "tail -f /dev/null"