name: 2 Tier

on:
  workflow_dispatch:

jobs:
  job-one:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # Output for the below command
      # /home/vagrant/actions-runner/_work/DNS-Container/DNS-Container
      - name: Print Working Directory
        run: pwd  

      - name: Change Working Directory & Print dockerfile
        run: | 
          cd 2tier
          cat dockerfile