name: 2 Tier

on:
  workflow_dispatch:

jobs:
  job-one:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Output for the below command
      # /home/vagrant/actions-runner/_work/DNS-Container/DNS-Container
      - name: Print Working Directory
        run: pwd

      - name: Change Working Directory & Print dockerfile
        run: |
          cd 2tier
          cat dockerfile

      - name: Configure Virtual Machine's DNS resolver to reach internet
        run: sudo sh -c 'printf "nameserver 8.8.8.8\nnameserver 1.1.1.1\n" > /etc/resolv.conf'

      # The below command did not go to 2tier
      - name: Docker Build Image
        run: |
          cd 2tier
          docker build --tag 2tier:latest .

      # The below command might have to include error handling
      - name: Docker Remove Existing 2tier Container
        run: |
          cd 2tier
          docker stop 2tier
          docker rm 2tier
      
      - name: Docker Run 2tier app
        run: |
          cd 2tier
          docker run --detach \
          --name=2tier \
          --privileged \
          --restart=always \
          --publish 0.0.0.0:80:80/tcp \
          --publish 0.0.0.0:3306:3306/tcp \
          2tier:latest bash -c "tail -f /dev/null"

      - name: Docker start mariadb & apache
        run: |
          cd 2tier
          docker exec -it 2tier bash
          bash start.sh
          ss -tulpn
